rules:
  # Kotlin/Java security rules for Ktor backend
  - id: hardcoded-credentials-kotlin
    patterns:
      - pattern: val password = "..."
      - pattern: val secret = "..."
      - pattern: val token = "..."
      - pattern: val apiKey = "..."
      - pattern: const val PASSWORD = "..."
      - pattern: const val SECRET = "..."
      - pattern: const val TOKEN = "..."
      - pattern: const val API_KEY = "..."
    message: "Hardcoded credentials detected in Kotlin code"
    languages: [kotlin]
    severity: ERROR

  - id: ktor-cors-allow-all
    patterns:
      - pattern: anyHost()
    message: "CORS configured to allow all hosts - consider restricting in production"
    languages: [kotlin]
    severity: WARNING

  - id: test-secret-in-production
    patterns:
      - pattern: '"Test"'
      - pattern: '"TestKey"'
    message: "Test secrets should not be used in production"
    languages: [kotlin]
    severity: INFO
