ktor {
    deployment {
        port = 5000
        port = ${?PORT}
    }
    application {
        modules = [ com.ultraviolince.mykitchen.server.ApplicationKt.module ]
    }
}

database {
    url = "jdbc:postgresql://localhost:5432/mykitchen"
    url = ${?DATABASE_URL}
    driver = "org.postgresql.Driver"
    user = "mykitchen"
    user = ${?DATABASE_USER}
    password = "mykitchen"
    password = ${?DATABASE_PASSWORD}
}

jwt {
    secret = "dev-secret-change-in-production"
    secret = ${?JWT_SECRET}
    issuer = "mykitchen"
    audience = "mykitchen-users"
    realm = "My Kitchen"
}
