name: Check Final Newlines

# Check that all source files end with a newline character
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  check-final-newlines:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Check for files without final newlines
      run: |
        # Find all source files and check if they end with a newline
        files_without_newlines=()
        
        while IFS= read -r -d '' file; do
          # Skip empty files - they're allowed to not have newlines
          if [ ! -s "$file" ]; then
            continue
          fi
          
          # Check if the file ends with a newline (0x0a)
          if [ "$(tail -c1 "$file" | od -A n -t x1)" != " 0a" ]; then
            files_without_newlines+=("$file")
          fi
        done < <(find . -type f \( \
          -name "*.kt" -o \
          -name "*.java" -o \
          -name "*.py" -o \
          -name "*.yml" -o \
          -name "*.yaml" -o \
          -name "*.md" -o \
          -name "*.gradle" -o \
          -name "*.kts" -o \
          -name "*.properties" -o \
          -name "*.json" -o \
          -name "*.txt" -o \
          -name "*.sh" \
        \) ! -path "./.git/*" ! -path "./build/*" ! -path "./.gradle/*" -print0)
        
        if [ ${#files_without_newlines[@]} -gt 0 ]; then
          echo "❌ The following files do not end with a newline:"
          printf '%s\n' "${files_without_newlines[@]}"
          echo ""
          echo "To fix this, add a newline at the end of each file."
          echo "You can use: echo \"\" >> filename"
          exit 1
        else
          echo "✅ All source files end with a newline character."
        fi
