name: Lint Commit Messages

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches: [main]

jobs:
  commitlint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 0  # Needed so we can access all commits

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: npm install

      - name: Lint commit messages
        run: |
          BASE_BRANCH=origin/${{ github.event.pull_request.base.ref }}
          MERGE_BASE=$(git merge-base HEAD "$BASE_BRANCH")
          npx commitlint --from="$MERGE_BASE" --to=HEAD
