name: Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 17

    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2

    - name: Build APKs
      run: ./gradlew :app:assembleRelease

    - name: Publish release
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        # TODO fix app signing
        files: |
          ${{runner.workspace}}/my-kitchen/app/build/outputs/apk/release/app-release.apk
        fail_on_unmatched_files: true

