name: Release

on:
  push:
    branches:
      - main
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v5
      with:
        fetch-depth: 0  # Fetch all history for git describe

    - uses: actions/setup-java@v5
      with:
        distribution: temurin
        java-version: 17

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4

    - name: Setup GitHub CLI
      run: |
        # GitHub CLI is pre-installed on GitHub Actions runners
        gh --version

    - name: Determine release type and version
      id: release_info
      run: |
        if [[ "${GITHUB_REF}" == refs/tags/* ]]; then
          echo "is_tag_release=true" >> $GITHUB_OUTPUT
          echo "version_name=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
          echo "is_snapshot=false" >> $GITHUB_OUTPUT
        else
          # Get the latest released version and add -rc suffix
          LATEST_TAG=$(git describe --tags --abbrev=0 --match="v*.*.*" 2>/dev/null || echo "v1.0.0")
          echo "is_tag_release=false" >> $GITHUB_OUTPUT
          echo "version_name=${LATEST_TAG}-rc" >> $GITHUB_OUTPUT
          echo "is_snapshot=true" >> $GITHUB_OUTPUT
        fi
        echo "version_code=$(git rev-list --count HEAD)" >> $GITHUB_OUTPUT

    - name: Delete existing release candidate
      if: steps.release_info.outputs.is_tag_release == 'true'
      run: |
        # Find and delete any existing RC release
        LATEST_TAG=$(git describe --tags --abbrev=0 --match="v*.*.*")
        RC_TAG="${LATEST_TAG}-rc"

        # Check if RC release exists and delete it
        if gh release view "$RC_TAG" &>/dev/null; then
          echo "Deleting existing release candidate: $RC_TAG"
          gh release delete "$RC_TAG" --yes --cleanup-tag
        fi
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Build APK for release candidate
      if: steps.release_info.outputs.is_tag_release == 'false'
      run: |
        ./gradlew :app:assembleRelease \
          -PversionCode=${{ steps.release_info.outputs.version_code }} \
          -PversionName=${{ steps.release_info.outputs.version_name }} \
          -PsnapshotBuild=true

    - name: Build APK for tag release
      if: steps.release_info.outputs.is_tag_release == 'true'
      run: |
        ./gradlew :app:assembleRelease \
          -PversionCode=${{ steps.release_info.outputs.version_code }} \
          -PversionName=${{ steps.release_info.outputs.version_name }}

    - name: Create git tag for release candidate
      if: steps.release_info.outputs.is_tag_release == 'false'
      run: |
        # Configure git for tag creation
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        
        # Create and push the tag
        git tag ${{ steps.release_info.outputs.version_name }}
        git push origin ${{ steps.release_info.outputs.version_name }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Create or update release candidate
      if: steps.release_info.outputs.is_tag_release == 'false'
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ steps.release_info.outputs.version_name }}
        name: "Release Candidate ${{ steps.release_info.outputs.version_name }}"
        body: |
          🚧 **Release Candidate** 🚧

          This is a release candidate build from the latest main branch.

          **Features:**
          - Uses debug app name and icon for easy identification
          - Side-by-side installation with production releases
          - Built from commit: ${{ github.sha }}

          This release candidate will be automatically archived when the corresponding production release is published.
        files: |
          app/build/outputs/apk/release/app-release.apk
        prerelease: true
        fail_on_unmatched_files: true

    - name: Publish production release
      if: steps.release_info.outputs.is_tag_release == 'true'
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ steps.release_info.outputs.version_name }}
        name: "Release ${{ steps.release_info.outputs.version_name }}"
        body: |
          🎉 **Production Release** 🎉

          This is a production release built from tag ${{ steps.release_info.outputs.version_name }}.

          **What's included:**
          - Production app configuration
          - Optimized and minified APK
          - Signed with release key

          Built from commit: ${{ github.sha }}
        files: |
          app/build/outputs/apk/release/app-release.apk
        fail_on_unmatched_files: true
