name: Tests

# Only pushes and PRs against the main branch are built
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

concurrency:
    group: ${{ github.head_ref || github.run_id }}
    cancel-in-progress: true

env:
    JAVA_VERSION: 17

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5
      with:
        lfs: 'true'

    - uses: actions/setup-java@v5
      with:
        distribution: temurin
        java-version: ${{ env.JAVA_VERSION }}

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4

    - name: Check build health
      run: ./gradlew buildHealth --warning-mode=fail

    - name: Build and run tests
      run: ./gradlew :app:assembleDebug :app:assembleRelease :app:testDebugUnitTest :app:verifyRoborazziDebug :app:koverXmlReportDebug detekt --warning-mode=fail

    - name: Build web app (JavaScript)
      run: ./gradlew :shared:jsBrowserDistribution --warning-mode=fail

    - name: Add coverage report to PR
      id: kover
      uses: mi-kas/kover-report@v1.9
      with:
        path: |
          ${{ github.workspace }}/app/build/reports/kover/reportDebug.xml
        token: ${{ secrets.COMMENTS_TOKEN }}
        title: Code Coverage
        update-comment: true
        min-coverage-overall: 10
        min-coverage-changed-files: 80
        coverage-counter-type: LINE


  ios:
    runs-on: macos-latest
    needs: build

    steps:
    - uses: actions/checkout@v5
      with:
        lfs: 'true'

    - uses: actions/setup-java@v5
      with:
        distribution: temurin
        java-version: ${{ env.JAVA_VERSION }}

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4

    - name: Build iOS framework for device and simulator
      run: |
        echo "Building iOS frameworks for all architectures..."
        ./gradlew shared:linkDebugFrameworkIosArm64 shared:linkDebugFrameworkIosX64 shared:linkDebugFrameworkIosSimulatorArm64 --warning-mode=fail
        echo "Verifying frameworks were built..."
        find shared/build -name "SharedKit.framework" -type d
        echo "Framework contents and architectures:"
        for framework in $(find shared/build -name "SharedKit.framework" -type d); do
          echo "Framework: $framework"
          ls -la "$framework"
          if [ -f "$framework/SharedKit" ]; then
            echo "Binary architectures:"
            file "$framework/SharedKit" || lipo -info "$framework/SharedKit" || echo "Could not determine architecture"
          fi
          echo "---"
        done

    - name: Run iOS Kotlin/Native tests
      run: ./gradlew shared:iosX64Test shared:iosSimulatorArm64Test --warning-mode=fail

    - name: List available schemes and build iOS app
      run: |
        cd iosApp
        echo "Available schemes:"
        xcodebuild -project iosApp.xcodeproj -list
        echo "Available simulators:"
        xcrun simctl list devices available --json | jq '.devices | to_entries[] | select(.value | length > 0) | .key + ": " + (.value | map(.name) | join(", "))'
        echo "Building iOS app..."
        xcodebuild -project iosApp.xcodeproj -scheme iosApp -destination 'platform=iOS Simulator,name=iPhone SE (3rd generation),OS=latest' build


  instrumentedtests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
          api-level: [28, 31, 34, 35]

    steps:
      - uses: actions/checkout@v5

      # Setup the test backend
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.13'

      - name: Install python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/image/requirements.txt

      - name: Start Flask server
        run: |
          export RECIPES_SECRET_KEY=TestKey
          python3 backend/image/app.py backend/seed_data &
        env:
          FLASK_ENV: development

      - name: Wait for Flask server to start
        run: |
          sleep 5
          curl --fail http://localhost:5000/health

      ## Run the instrumented tests
      - name: Get AVD info
        uses: ./.github/actions/get-avd-info
        id: avd-info
        with:
            api-level: ${{ matrix.api-level }}

      - name: Enable KVM group perms
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm
          ls /dev/kvm

      - uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: ${{ env.JAVA_VERSION }}

      - uses: gradle/actions/setup-gradle@v4

      - name: Run Tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          arch: ${{ steps.avd-info.outputs.arch }}
          target: ${{ steps.avd-info.outputs.target }}
          script: ./gradlew connectedCheck --stacktrace
        env:
          API_LEVEL: ${{ matrix.api-level }}

